Login Component
cfernando415/femmecubator-ui-repo pull request #57
Opened 2020-12-05 20:46 UTC by PeaWarrior

**Desktop View**
<img width="1479" alt="desktop" src="https://user-images.githubusercontent.com/53205189/101263126-f9824280-3710-11eb-9880-2737abd1309d.png">
<img width="1479" alt="desktop-error" src="https://user-images.githubusercontent.com/53205189/101263127-fab36f80-3710-11eb-8645-d178ed8b423d.png">
**Mobile View**
<img width="386" alt="mobile" src="https://user-images.githubusercontent.com/53205189/101263131-fbe49c80-3710-11eb-92c8-8f46a069caf9.png">
<img width="386" alt="mobile-error" src="https://user-images.githubusercontent.com/53205189/101263132-fc7d3300-3710-11eb-886a-7fda4d76754d.png">

2020-12-05 20:48 UTC, PeaWarrior commented
Tests
<img width="552" alt="Screen Shot 2020-12-05 at 3 47 55 PM" src="https://user-images.githubusercontent.com/53205189/101263170-4a923680-3711-11eb-8099-e9bb4b19f36c.png">

2020-12-05 21:43 UTC, cfernando415 requested changes
please changes requested

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +  pattern: /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
### Change to:

`required: 'Email is required',
  pattern: {
    value: /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    message: 'Invalid email format',
  },`

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +
### Changes:

`import isEmpty from 'lodash/isEmpty';`

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +    request.post(API_PATH.LOGIN, credentials).then((response) => {
### Changes:
`then(({ status })) =>`

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +      if (response.status === 200) {
`if(status === 200)`

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +            />
same es6 changes

2020-12-05 21:43 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +          )}
### Changes:
we also want the error to be driven by query params and show the session timeout if the url has timedOut=true, for example https://femmecubator.com/login?timedOut=true

**Timed Out Session**
![image](https://user-images.githubusercontent.com/42846522/101265942-e4111680-3718-11eb-9f7c-33b866f296b8.png)

2020-12-05 23:41 UTC, cfernando415 requested changes
almost there

2020-12-05 23:41 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +                error: !isEmpty(errors.email) && true,
remove true !isEmpty(errors.email) will resolve to true if errors.email is empty

2020-12-05 23:41 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +                error: !isEmpty(errors.password) && true,
same comment as previous one

2020-12-05 23:41 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +                        onClick={handleClickShowPassword}
`{...{ 'aria-label': 'toggle password visibility', edge: 'end', onClick: handleClickShowPassword }}`

2020-12-06 02:02 UTC, cfernando415 requested changes
please see comment

2020-12-06 02:02 UTC, cfernando415 commented on src/components/AccountForms/LoginForm/index.js
> +          {isEmpty(errors) && search === '?timedOut=true' && (
### Change requested:
- used the extracted value of the query string here

`{isEmpty(errors) && timedOut && (`     ....

2020-12-06 03:24 UTC, cfernando415 approved these changes
👍

2020-12-06 03:24 UTC, merged